OOP school library: unit tests
AmanWorku/OOP-School-Library pull request #7
Opened 2023-03-22 14:51 UTC by Salwa99

# OOP school library: unit tests

### Howdy! :cowboy_hat_face: 

**In this PR We :**

1. Write unit tests using `Rspec` for the following classes : 

    - `Book`
    - `Person`
    - `Student`
    - `Teacher`
    - `Classroom`
    - `Rental`

2. Follow GitFlow.
3. Fix Linter errors.

_Cheers! :rose:_

2023-03-22 15:22 UTC, VICTOR-CHUKWU requested changes
Hi Team 👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 15:22 UTC, VICTOR-CHUKWU commented on spec/person_spec.rb
> +end
- [ ] you should try and test a good number of the features in the person class e. test to show that rental is added to person,  test to show `The constructor method sets default value for the optional name parameter if it is not provided`, I can not see test to validate correct name. kindly add it too
```
it "The add_rental method returns a rental and adds its to the book" do
      book = Book.new("Title", "Author")
      person = Person.new(24, "Bob")

      rental = person.add_rental(book, "2021-05-04")

      expect(person.rentals).to eql [rental]
    end
```

2023-03-22 15:22 UTC, VICTOR-CHUKWU commented on spec/book_spec.rb
> +    end
- [ ] kindly add a test to show that rental is added to a book

2023-03-22 18:06 UTC, bimbolabuari reviewed
Hello Team 👋,

_This is an additional review as a result of the second opinion request._

- Kudos on working on this milestone 👍 
    - As part of the project requirement:
       - There is a requirement to add unit tests for all the methods in all the classes(`Book`, `Person`, `Student`, `Teacher`, `Classroom`, `Rental`:

- In your `book.rb`, there is an add rental method that was not tested.
  - https://github.com/AmanWorku/OOP-School-Library/blob/87561ee551364513ecce9bf407cce85296754a2d/book.rb#L8-L10

- Also in your `person.rb`, there are some method that were not tested as required.
 - https://github.com/AmanWorku/OOP-School-Library/blob/87561ee551364513ecce9bf407cce85296754a2d/person.rb#L23-L25
 - https://github.com/AmanWorku/OOP-School-Library/blob/87561ee551364513ecce9bf407cce85296754a2d/person.rb#L27-L29
 - https://github.com/AmanWorku/OOP-School-Library/blob/87561ee551364513ecce9bf407cce85296754a2d/person.rb#L31-L39
 - https://github.com/AmanWorku/OOP-School-Library/blob/87561ee551364513ecce9bf407cce85296754a2d/person.rb#L41-L43
 - https://github.com/AmanWorku/OOP-School-Library/blob/87561ee551364513ecce9bf407cce85296754a2d/person.rb#L19-L21

- Currently, you instantiate the classes ("Note: The phrase "instantiating a class" means the same thing as "creating an object." When you create an object, you are creating an "instance" of a class, therefore "instantiating" a class.") and test for the new object variable 

- Let's check this [previous exercise link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/rspec_unit_test.md#unit-testing) for more knowledge of unit testing and please let's make the requested changes asked by the previous code reviewer. 👍 


Keep rocking 🚀!

2023-03-23 15:55 UTC, frank1738 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-medium.gif"/>

## Highlights

✅ Correct use of Gitflow
✅ No linter error



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 15:55 UTC, frank1738 commented on spec/rental_spec.rb
> +    end
- [ ] Good work adding tests but some tests are failing. Kindly check them out

![image](https://user-images.githubusercontent.com/98453979/227261017-1f91b872-1147-4de6-bae0-7572f292e993.png)

2023-03-23 16:03 UTC, Salwa99 commented on spec/rental_spec.rb
> +    end
Hi @frank1738 , I can't see any errors in out tests
![Screenshot from 2023-03-23 16-01-52](https://user-images.githubusercontent.com/110976050/227263674-3ea91429-e3e3-4a6e-b74b-350cfcb88cf5.png)

2023-03-23 17:47 UTC, addod19 approved these changes
### Hi @AmanWorku and @Salwa99, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] All test cases passed :rocket: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 18:15 UTC, AmanWorku commented
Thank you @addod19.

2023-03-23 18:15 UTC, merged